CRUD/Models/ErrorViewModel.cs
using System;

namespace CRUD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD/Models/ResponseWebApi.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CRUD.Database;
namespace CRUD.Models
{
    public class ResponseWebApi
    {
          public int CodigoRespuesta { get; set; }
          public string MensajeRespuesta { get; set; }

    }
    public class ResponseWebApiLista<T> :  ResponseWebApi
    {
        public IEnumerable<T> listaUsuarios { get; set; }
    }
}

CRUD/Controllers/Apis/CrudWebApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CRUD.Database.Logical;
using CRUD.Database;
using CRUD.Models;
namespace CRUD.Controllers.Apis
{
    [Route("api/[controller]")]
    [ApiController]
    
    public class CrudWebApi : ControllerBase
    {
        private readonly ICrud<Usuarios> CrudImplementacion;
        
        public CrudWebApi(ICrud<Usuarios> cr)
        {
            CrudImplementacion = cr;
            
        }


        [HttpGet]
        public async Task<ActionResult<ResponseWebApiLista<Usuarios>>> ObtenerTodos()
        {
            ResponseWebApiLista<Usuarios> respuesta = new ResponseWebApiLista<Usuarios>();
            try
            {
                respuesta.listaUsuarios = CrudImplementacion.ObtenerTodos();
                respuesta.CodigoRespuesta = 1;
                respuesta.MensajeRespuesta = "Se cargaron todos los usuarios en la bd";
                return respuesta;
            }
            catch (Exception e)
            {
                respuesta.CodigoRespuesta = 3;
                respuesta.MensajeRespuesta = "Error " + e.Message;
                return respuesta;
            }
        }


        [HttpPost]
        public async Task<ActionResult<ResponseWebApi>> RegistrarUsuario(Usuarios user)
        {
            ResponseWebApi respuesta = new ResponseWebApi();
            try
            {
                if (ModelState.IsValid)
                {
                    CrudImplementacion.Crear(user);
                    Response.StatusCode = 201;
                    respuesta.CodigoRespuesta = 1;
                    respuesta.MensajeRespuesta = "se creo el usuario correctamente ";
                    return respuesta;
                }
                respuesta.CodigoRespuesta = 2;
                respuesta.MensajeRespuesta = "No se creo el usuario, error en el modelo de ingreso";
                return respuesta;
            }
            catch (Exception e)
            {
                respuesta.CodigoRespuesta = 3;
                respuesta.MensajeRespuesta = "Error " + e.Message;
                return respuesta;
            }
        }

        
        [HttpPut("{id}")]
        public async Task<ActionResult<ResponseWebApi>> ActualizarRegistro(Usuarios user)
        {
            ResponseWebApi respuesta = new ResponseWebApi();

            try
            {
                if (ModelState.IsValid)
                {
                    CrudImplementacion.Actualizar(user);
                    Response.StatusCode = 200;
                    respuesta.CodigoRespuesta = 1;
                    respuesta.MensajeRespuesta = "se Actualizo el usuario correctamente";
                    return respuesta;
                }
                respuesta.CodigoRespuesta = 2;
                respuesta.MensajeRespuesta = "No se creo el usuario, error en el modelo de ingreso";
                return respuesta;

            }
            catch (Exception e)
            {
                respuesta.CodigoRespuesta = 3;
                respuesta.MensajeRespuesta = "Error " + e.Message;
                return respuesta;

            }

        }

        
        [HttpDelete("{id}")]
        public async Task<ActionResult<ResponseWebApi>> EliminarUsuario(decimal id)
        {
            ResponseWebApi respuesta = new ResponseWebApi();
            try
            {

                CrudImplementacion.Eliminar(id);
                Response.StatusCode = 200;
                respuesta.CodigoRespuesta = 1;
                respuesta.MensajeRespuesta = "se Elimino el usuario correctamente";
                return respuesta;

            }
            catch (Exception e)
            {
                respuesta.CodigoRespuesta = 3;
                respuesta.MensajeRespuesta = "Error " + e.Message;
                return respuesta;

            }

        }
    }
}

CRUD/Controllers/Apis/UtilidadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CRUD.Database;
using CRUD.Database.Logical;
using CRUD.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CRUD.Controllers.Apis
{
    [Route("api/[controller]")]
    [ApiController]
    public class UtilidadesController : ControllerBase
    {
        private readonly IUtlidades utilidadesImplementacion;
        public UtilidadesController(IUtlidades iu)
        {
            utilidadesImplementacion = iu;
        }


        [HttpGet]
        public async Task<ActionResult<ResponseWebApiLista<TipoIdentificacion>>> ObtenerTodosTiposIdentificacion()
        {
            ResponseWebApiLista<TipoIdentificacion> respuesta = new ResponseWebApiLista<TipoIdentificacion>();
            try
            {
                respuesta.listaUsuarios = utilidadesImplementacion.getAllTiposIdentificacion();
                respuesta.CodigoRespuesta = 1;
                respuesta.MensajeRespuesta = "Se cargaron todos los usuarios en la bd";
                return respuesta;
            }
            catch (Exception e)
            {
                respuesta.CodigoRespuesta = 3;
                respuesta.MensajeRespuesta = "Error " + e.Message;
                return respuesta;
            }
        }



    }
}

CRUD/Controllers/CrudDashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CRUD.Controllers
{
    
    public class CrudDashBoardController : Controller
    {
        public ActionResult Home()
        {
            return View();
        }


        public ActionResult Crear()
        {
            return View();
        }
    }
}

CRUD/Views/CrudDashBoard/Crear.cshtml
@{
    ViewData["Title"] = "Crear";
}


<div class="card">
    <div class="card-header">
        <h2>Creacion Usuario</h2>
    </div>
    <div class="card-body">

        <div class="col-sm-5 messages"></div>
        <form method="post" class="form_crud" id="registro">
            <div class="form-group">
                <label for="tipoId">
                    TipoIdentificacion :
                    <select id="tipoId" name="tipoId">
                    </select>
                </label>
                <div class="col-sm-5 mensaje"></div>
            </div>

            <div class="form-group">
                <label for="cedula">
                    Cedula :
                    <input type="text" id="cedula" class="form-control" name="cedula" />
                </label>
                <div class="col-sm-5 mensaje"></div>

            </div>
            <div class="form-group">

                <label for="nombre">
                    Nombre :
                    <input type="text" id="nombre" class="form-control" name="nombre" />
                </label>
                <div class="col-sm-5 mensaje"></div>
            </div>
            <div class="form-group">

                <label for="apellido">
                    Apellido :
                    <input type="text" id="apellido" class="form-control" name="apellido" />
                </label>
                <div class="col-sm-5 mensaje"></div>
            </div>
            <div class="form-group">

                <label for="email">
                    Email :
                    <input type="email" id="email" class="form-control" name="email" />
                </label>
                <div class="col-sm-5 mensaje"></div>

            </div>
            <div class="form-group">

                <label for="password">
                    Password :
                    <input type="password" id="password" class="form-control" name="password" />
                </label>
                <div class="col-sm-5 mensaje"></div>

            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-3">
                        <button type="submit" class="btn btn-success">Crear Usuario</button>
                    </div>

                    <div class="col-md-3">
                        <button type="button" id="limpiarForm" class="btn btn-success">Limpiar formulario</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@Html.ActionLink("Regresar al Menu Principal",  "Home", "CrudDashBoard")

@section Scripts
{
    <script src="~/js/usuarios.js" type="text/javascript"></script>
}

CRUD/Views/CrudDashBoard/Home.cshtml
@{
    ViewData["Title"] = "Home";
}



    <div class="card">

        
        <div class="card-header">
            <h2>Usuario Reportados</h2>
        </div>
        

        <div class="card-body">
            <div id="editForm">
                <h3>Editar Usuario</h3>
                <form id="EditarForm" action="javascript:void(0);">
                    <input type="hidden" id="edit-id">
                    <input type="hidden" id="edit-tipoId">
                    <input type="hidden" id="edit-contraseña">
                    <input type="text" id="edit-nombre">
                    <input type="text" id="edit-apellido">
                    <input type="text" id="edit-email">
                    <input type="submit" value="Guardar">
                    <a id="linkclose" aria-label="Close">&#10006;</a>
                </form>
            </div>
            <a href="@Url.ActionLink("Crear", "CrudDashBoard")">Crear Nuevo Usuario </a>
            <table class="table table-bordered " id="tabla_usuarios">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Email</th>
                        <th>Operacion</th>

                    </tr>

                </thead>
                <tbody id="usuariosBody">
                </tbody>
            </table>
        </div>
    </div>
@section Scripts
{
    <script src="~/js/home.js"></script>
}

CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/validate/validate.min.js"></script>
    <script src="~/lib/validate/underscore-min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    
    
    @RenderSection("Scripts", required: false)
</body>
</html>